version: '3'

services:
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - app-network

  nodejs:
    image: node:alpine
    container_name: backend
    build: .
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    ports:
      - 3333:3333
    command: ['yarn', 'start']
    restart: unless-stopped
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3333
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
