version: '3'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  app:
    build: .
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    command: ['yarn', 'start']
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
